"""add_subscription_licensing

Revision ID: 52e29e4dd2a9
Revises: 37417ee7444e
Create Date: 2026-05-01 15:32:37.109989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e29e4dd2a9'
down_revision: Union[str, Sequence[str], None] = '37417ee7444e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('vat_condition', sa.String(length=50), nullable=True),
    sa.Column('total_licenses', sa.Integer(), nullable=False),
    sa.Column('used_licenses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mp_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('internal_code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('mp_plan_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('unit_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("billing_period IN ('monthly', 'annual')", name='ck_mp_plan_period'),
    sa.CheckConstraint("type IN ('individual', 'institutional')", name='ck_mp_plan_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_code')
    )
    op.create_table('users_profile',
    sa.Column('clerk_user_id', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('vat_condition', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('educational_centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_tenant_id'], ['institution_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profile.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_centers_user_id'), 'educational_centers', ['user_id'], unique=False)
    op.create_table('individual_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('mp_plan_id', sa.String(length=36), nullable=False),
    sa.Column('mp_preapproval_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('authorized', 'paused', 'cancelled')", name='ck_sub_status'),
    sa.ForeignKeyConstraint(['mp_plan_id'], ['mp_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profile.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_subscriptions_user_id'), 'individual_subscriptions', ['user_id'], unique=False)
    op.create_table('institution_billing_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_tenant_id', sa.String(length=36), nullable=False),
    sa.Column('mp_plan_id', sa.String(length=36), nullable=False),
    sa.Column('license_count', sa.Integer(), nullable=False),
    sa.Column('unit_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('mp_preference_id', sa.String(length=100), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'overdue', 'failed')", name='ck_billing_status'),
    sa.ForeignKeyConstraint(['institution_tenant_id'], ['institution_tenants.id'], ),
    sa.ForeignKeyConstraint(['mp_plan_id'], ['mp_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_billing_cycles_institution_tenant_id'), 'institution_billing_cycles', ['institution_tenant_id'], unique=False)
    op.create_table('institution_tenant_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_tenant_id'], ['institution_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_tenant_units_institution_tenant_id'), 'institution_tenant_units', ['institution_tenant_id'], unique=False)
    op.create_table('institution_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('institution_tenant_id', sa.String(length=36), nullable=False),
    sa.Column('institution_unit_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'teacher')", name='ck_member_role'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_member_status'),
    sa.ForeignKeyConstraint(['institution_tenant_id'], ['institution_tenants.id'], ),
    sa.ForeignKeyConstraint(['institution_unit_id'], ['institution_tenant_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profile.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_tenant_id', name='uq_member_user_tenant')
    )
    op.create_index(op.f('ix_institution_members_institution_tenant_id'), 'institution_members', ['institution_tenant_id'], unique=False)
    op.create_index(op.f('ix_institution_members_user_id'), 'institution_members', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('billing_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('zsoft_cfe_id', sa.String(length=100), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_cycle_id'], ['institution_billing_cycles.id'], ),
    sa.ForeignKeyConstraint(['institution_tenant_id'], ['institution_tenants.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['individual_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profile.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_tenant_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('institution_unit_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('available', 'assigned', 'suspended')", name='ck_license_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users_profile.clerk_user_id'], ),
    sa.ForeignKeyConstraint(['institution_tenant_id'], ['institution_tenants.id'], ),
    sa.ForeignKeyConstraint(['institution_unit_id'], ['institution_tenant_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_institution_tenant_id'), 'licenses', ['institution_tenant_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('educational_center_id', sa.String(length=36), nullable=True),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('grado', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['educational_center_id'], ['educational_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=False)
    # alumnos → students: drop old table only if it exists (prod DBs with existing data)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'alumnos' in inspector.get_table_names():
        op.drop_index(op.f('ix_alumnos_id'), table_name='alumnos')
        op.drop_index(op.f('ix_alumnos_user_id'), table_name='alumnos')
        op.drop_table('alumnos')
    with op.batch_alter_table('planificaciones') as batch_op:
        batch_op.add_column(sa.Column('educational_center_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_planificaciones_educational_center', 'educational_centers', ['educational_center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificaciones') as batch_op:
        batch_op.drop_constraint('fk_planificaciones_educational_center', type_='foreignkey')
        batch_op.drop_column('educational_center_id')
    op.create_table('alumnos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('nombre_completo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('fecha_nacimiento', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nivel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('grado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notas', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnos_user_id'), 'alumnos', ['user_id'], unique=False)
    op.create_index(op.f('ix_alumnos_id'), 'alumnos', ['id'], unique=False)
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_licenses_institution_tenant_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_institution_members_user_id'), table_name='institution_members')
    op.drop_index(op.f('ix_institution_members_institution_tenant_id'), table_name='institution_members')
    op.drop_table('institution_members')
    op.drop_index(op.f('ix_institution_tenant_units_institution_tenant_id'), table_name='institution_tenant_units')
    op.drop_table('institution_tenant_units')
    op.drop_index(op.f('ix_institution_billing_cycles_institution_tenant_id'), table_name='institution_billing_cycles')
    op.drop_table('institution_billing_cycles')
    op.drop_index(op.f('ix_individual_subscriptions_user_id'), table_name='individual_subscriptions')
    op.drop_table('individual_subscriptions')
    op.drop_index(op.f('ix_educational_centers_user_id'), table_name='educational_centers')
    op.drop_table('educational_centers')
    op.drop_table('users_profile')
    op.drop_table('mp_plans')
    op.drop_table('institution_tenants')
    # ### end Alembic commands ###
